name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: actions/cache@v3
      id: gradle-cache
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - uses: actions/cache@v3
      id: gradle-wrapper-cache
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --info
    - name: Dependency check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: dependencyCheckAnalyze
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.7.0
